<?php

namespace AppBundle\Repository;

/**
 * AccountNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
