<?php

namespace AppBundle\Repository;

/**
 * ChannelSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelSupportRepository extends \Doctrine\ORM\EntityRepository
{
}
