<?php

namespace AppBundle\Repository;

/**
 * ClientNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
