<?php

namespace AppBundle\Repository;

/**
 * CommissionTierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionTierRepository extends \Doctrine\ORM\EntityRepository
{
}
