<?php

namespace AppBundle\Repository;

/**
 * CommissionModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionModelRepository extends \Doctrine\ORM\EntityRepository
{
}
