<?php

namespace AppBundle\Repository;

/**
 * ContractServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
