<?php

namespace AppBundle\Repository;

/**
 * DataAcquisitionProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataAcquisitionProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
