<?php

namespace AppBundle\Repository;

/**
 * DataAcquisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataAcquisitionRepository extends \Doctrine\ORM\EntityRepository
{
}
