<?php

namespace AppBundle\Repository;

/**
 * LeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLeadsByDates($startDate, $endDate)
    {
        return $this->createQueryBuilder('l')
            ->where('l.createdAt >= :startDate')
            ->andWhere('l.createdAt <= :endDate')
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->getQuery()
            ->getResult();
    }
}
