<?php

namespace AppBundle\Repository;

/**
 * LeadTrackerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadTrackerRepository extends \Doctrine\ORM\EntityRepository
{
}
