<?php

namespace AppBundle\Repository;

/**
 * LeadStatusLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadStatusLogRepository extends \Doctrine\ORM\EntityRepository
{
}
