<?php

namespace AppBundle\Repository;

/**
 * LeadNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
