<?php

namespace AppBundle\Repository;

/**
 * LocationTimetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationTimetableRepository extends \Doctrine\ORM\EntityRepository
{
}
