<?php

namespace AppBundle\Repository;

/**
 * MinimumVolumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinimumVolumeRepository extends \Doctrine\ORM\EntityRepository
{
}
