<?php

namespace AppBundle\Repository;

/**
 * PotentialSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PotentialSupplierRepository extends \Doctrine\ORM\EntityRepository
{
}
