<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Contract;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $status
     *
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getContractSentSuppliersCount($status)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('COUNT (DISTINCT s.id)')
            ->join('s.contracts', 'c')
            ->where('c.status = :status')
            ->setParameter('status', $status);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
