<?php

namespace AppBundle\Repository;

/**
 * SupportFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
