<?php

namespace AppBundle\Repository;

/**
 * SupplierProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
