<?php

namespace AppBundle\Repository;

/**
 * SupplierNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
