<?php

namespace AppBundle\Repository;

/**
 * TenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenderRepository extends \Doctrine\ORM\EntityRepository
{
}
