<?php

namespace AppBundle\Form;

use AppBundle\Entity\WorkFromHome;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Range;

class WorkFromHomeType extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('country', ChoiceType::class, [
                'label' => 'Location of Work from Home Agents',
                'choices' => array_combine(WorkFromHome::getCountries(), WorkFromHome::getCountries()),
                'placeholder' => 'Please select country',
                'attr' => [
                    'class' => 'select2',
                    'data-placeholder' => 'Please select country',
                    'data-tags' => true
                ],
                'constraints' => [
                    new NotBlank()
                ],
                'required' => true
        ])
        ->add('fte', NumberType::class, [
            'label' => 'Total number of Full Time Equivalents (FTE)',
            'required' => true,
            'constraints' => [
                new NotBlank(),
                new Range(['min' => 0, 'max' => 5000])
            ],
            'attr' => [
                'class' => 'input-fte'
            ]
        ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'AppBundle\Entity\WorkFromHome'
        ]);
    }

    public function getBlockPrefix()
    {
        return 'WorkFromHomeType'; // TODO: Change the autogenerated stub
    }
}